package locadora.ui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import locadora.Main;
import locadora.dados.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marco
 */
public class InterfaceInicio extends javax.swing.JFrame {

    /**
     * Creates new form int_inicio
     */
    public InterfaceInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guia = new javax.swing.JTabbedPane();
        painelClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        painelFilmes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaFilmes = new javax.swing.JTable();
        painelBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExibirInfo = new javax.swing.JButton();
        painelPesquisa = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Locadora");

        guia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiaStateChanged(evt);
            }
        });

        tabelaClientes.setAutoCreateRowSorter(true);
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Data Última Locação"
            }
        ));
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaClientes.getTableHeader().setReorderingAllowed(false);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaClientes);

        javax.swing.GroupLayout painelClientesLayout = new javax.swing.GroupLayout(painelClientes);
        painelClientes.setLayout(painelClientesLayout);
        painelClientesLayout.setHorizontalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
        painelClientesLayout.setVerticalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        guia.addTab("Clientes", painelClientes);

        tabelaFilmes.setAutoCreateRowSorter(true);
        tabelaFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Data de Lançamento", "Qtd. Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFilmes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabelaFilmes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabelaFilmes.getTableHeader().setReorderingAllowed(false);
        tabelaFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaFilmes);

        javax.swing.GroupLayout painelFilmesLayout = new javax.swing.GroupLayout(painelFilmes);
        painelFilmes.setLayout(painelFilmesLayout);
        painelFilmesLayout.setHorizontalGroup(
            painelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
        painelFilmesLayout.setVerticalGroup(
            painelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        guia.addTab("Filmes", painelFilmes);

        painelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNovo.setText("Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(80, 22));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(80, 22));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSelecionar.setText("Selecionar");
        btnSelecionar.setEnabled(false);
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnDevolver.setText("Devolver");
        btnDevolver.setEnabled(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExibirInfo.setText("Exibir Info");
        btnExibirInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExibirInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver)
                .addGap(28, 28, 28)
                .addComponent(btnExibirInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        txtPesquisa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaCaretUpdate(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisa)
                .addContainerGap())
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        guia.getAccessibleContext().setAccessibleName("guia");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Main.BotaoNovo(guia.getSelectedIndex());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Main.BotaoExcluir(guia.getSelectedIndex(), tabelaClientes, tabelaFilmes);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        int index = tabelaClientes.convertRowIndexToModel(tabelaClientes.getSelectedRow());
        String cpf = (String)tabelaClientes.getValueAt(index, 1);
        Cliente cliente = Main.GetCliente(cpf);
            
        Object[] options = {"Sim", "Cancelar"};
        
        int n = JOptionPane.showOptionDialog(this,
            "Deseja devolver os filmes " + cliente.Locacao().ToString() + " para o cliente " + cliente.Nome() + "?",
            "Devolução",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
        
        
        if (n == 0) {
            cliente.Devolver();
            Main.AtualizarClientes();
            Main.AtualizarDVDs();
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        atualizarBotoesCliente();
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void guiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiaStateChanged
        if (guia.getSelectedIndex() == 0) {
            atualizarBotoesCliente();
        } else {
            atualizarBotoesFilme();
        }
    }//GEN-LAST:event_guiaStateChanged

    private void tabelaFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesMouseClicked
        if (clienteSelecionado == null) {
            atualizarBotoesFilme();
        } else {
            int[] selecionados = tabelaFilmes.getSelectedRows();
 
            if (selecionados.length > 0 && selecionados.length <= Locacao.quantidadeMax) {
                btnSelecionar.setEnabled(true);
            } else {
                btnSelecionar.setEnabled(false);
            }            
            
            for (int selecionado : selecionados) {
                int index = tabelaFilmes.convertRowIndexToModel(selecionado);
                String titulo = (String)tabelaFilmes.getValueAt(index, 0);
                    
                Map.Entry<DVD, Integer> dvd = Main.GetDVD(titulo);
                
                if (dvd.getValue() == 0) {
                    btnSelecionar.setEnabled(false);
                    return;
                }
            }          
        }
    }//GEN-LAST:event_tabelaFilmesMouseClicked

    Cliente clienteSelecionado;
    List<DVD> dvds;
    
    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (clienteSelecionado == null) {
            if (guia.getSelectedIndex() == 0) { // Salva o cliente em uma variável e troca de aba para selecionar o filme
                int index = tabelaClientes.convertRowIndexToModel(tabelaClientes.getSelectedRow());
                String cpf = (String)tabelaClientes.getValueAt(index, 1);
                clienteSelecionado = Main.GetCliente(cpf);

                javax.swing.JOptionPane.showMessageDialog(this, "Selecione o(s) filme(s) para alugar.");
                guia.setSelectedIndex(1);
                guia.setEnabledAt(0, false);
                
                btnCancelar.setEnabled(true);
                
                btnNovo.setEnabled(false);
                btnExcluir.setEnabled(false);                
            }
        } else {
            if (guia.getSelectedIndex() == 1) { // Seleciona o(s) filme(s) para alugar
                //tabelaFilmes.getSelectedRows();
                int[] selecionados = tabelaFilmes.getSelectedRows();
                
                dvds = new ArrayList<DVD>();
                
                for(int selecionado : selecionados) {
                    int index = tabelaFilmes.convertRowIndexToModel(selecionado);
                    String titulo = (String)tabelaFilmes.getValueAt(index, 0);
                    
                    Map.Entry<DVD, Integer> dvd = Main.GetDVD(titulo);
                    
                    dvds.add(dvd.getKey());
                }
                
                clienteSelecionado.Alugar(dvds, Main.Data());
                
                Main.AtualizarClientes();
                Main.AtualizarDVDs();
                
                javax.swing.JOptionPane.showMessageDialog(this, "O cliente " + clienteSelecionado.Nome() + " alugou " + clienteSelecionado.Locacao().ToString() + ".");
                guia.setEnabledAt(0, true);
                guia.setSelectedIndex(0);
                
                btnSelecionar.setEnabled(false);                
                btnCancelar.setEnabled(false);   
                
                btnNovo.setEnabled(true);            
                
                clienteSelecionado = null;
            }            
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteSelecionado = null;
        
        guia.setEnabledAt(0, true);
        guia.setEnabledAt(1, true);
        btnSelecionar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnNovo.setEnabled(true); 
        
        if (guia.getSelectedIndex() == 0)
            guia.setSelectedIndex(1);
        else
            guia.setSelectedIndex(0);        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        System.out.println("Action Performed");
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaCaretUpdate
        String text = txtPesquisa.getText();
                
        if (text.equals("") || text.equals(" ")) {
           if (guia.getSelectedIndex() == 0)
               Main.AtualizarClientes();
           else
               Main.AtualizarDVDs();
        } else {
            if (guia.getSelectedIndex() == 0)
                Main.AtualizarClientesPesquisa(text);     
            else
                Main.AtualizarDVDsPesquisa(text);  
        }        
    }//GEN-LAST:event_txtPesquisaCaretUpdate

    private void btnExibirInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirInfoActionPerformed
        int index = tabelaClientes.convertRowIndexToModel(tabelaClientes.getSelectedRow());
        String cpf = (String)tabelaClientes.getValueAt(index, 1);
        Cliente cliente = Main.GetCliente(cpf);
 
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        
        String informação = cliente.Nome() + " " + cliente.Sobrenome() + "    CPF: " + cliente.CPF() + "    Data de Nascimento: " + cliente.DataNascimento().format(formatter);       
        informação += "\nTelefone: " + cliente.Telefone();
        
        Endereco endereco = cliente.Endereco();
        
        informação += "    Endereço: " + endereco.logradouro + ", " + endereco.numero + "    " + endereco.complemento;
        
        informação += "\n" + endereco.cidade + ", " + endereco.bairro + "    " + endereco.cep;
        
        if (cliente.Locacao() != null)
            informação += "\n\nFilmes Alugados: " + cliente.Locacao().ToString();
        
        javax.swing.JOptionPane.showMessageDialog(this, informação);
    }//GEN-LAST:event_btnExibirInfoActionPerformed

    void atualizarBotoesCliente() {
        if (tabelaClientes.getSelectedRow() != -1) {
            int index = tabelaClientes.convertRowIndexToModel(tabelaClientes.getSelectedRow());
            String cpf = (String)tabelaClientes.getValueAt(index, 1);
            Cliente cliente = Main.GetCliente(cpf);
            
            if (cliente.Locacao() == null) {
                btnSelecionar.setEnabled(true);
                btnDevolver.setEnabled(false);
            } else {
                btnSelecionar.setEnabled(false);
                btnDevolver.setEnabled(true);
            }
                        
            //btnEditar.setEnabled(true);
            btnExibirInfo.setEnabled(true);
            btnExcluir.setEnabled(true);
        } else {
            btnExibirInfo.setEnabled(false);
        }
    }

    void atualizarBotoesFilme() {
        btnExibirInfo.setEnabled(false);
        
        btnSelecionar.setEnabled(false);
        btnDevolver.setEnabled(false);
         
        if (tabelaFilmes.getSelectedRow() != -1) {          
            //btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }

    public void AtualizarListaClientes(Object[][] tabela) {
        String[] colunas = new String[] {
            "Nome", "CPF", "Estado"
        };        

        DefaultTableModel model = new DefaultTableModel(tabela, colunas) {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        
        tabelaClientes.setModel(model);
    }
    
    public void AtualizarListaDVDs(Object[][] tabela) {
        String[] colunas = new String[] {
            "Nome", "Classificação", "Data de Lançamento", "Qtd. Disponível"
        };        

        DefaultTableModel model = new DefaultTableModel(tabela, colunas) {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        
        tabelaFilmes.setModel(model);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExibirInfo;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JTabbedPane guia;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelClientes;
    private javax.swing.JPanel painelFilmes;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaFilmes;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
